import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hansol_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css"
          rel="stylesheet"
        />
      </head>
      <body className="font-pretendard scroll-hidden">{children}</body>
    </html>
  );
}
